version: '3.7'

services:
  app:
    build:
      context: .
    ports:
      - '8000:8000'
    # user: '0' # uncomment to run as root for testing purposes even though Dockerfile defines 'vapor' user.
    # command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8000"]